/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package loaa_backend;

import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.SpringApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
    	SpringApplication.run(App.class, args);   
    }
}
